name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci_check:
    name: CI Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup dependencies
        run: uv sync --dev

      - name: Install Ruff
        run: curl -LsSf https://astral.sh/ruff/install.sh | sh

      - name: Code Format Check
        run: ruff format --check

      - name: Code Lint Check
        run: ruff check

      - name: Run Pytest
        run: |
          source .venv/bin/activate
          pytest

      - name: Try to run example
        run: |
          source .venv/bin/activate
          python3 examples/example.py
